# Generated by Django 3.0.2 on 2021-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='hood_logo',
            new_name='neighborhood_logo',
        ),
    ]
